# Generated by foundation-archetype
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY target/demo-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Djava.security.egd=file:/dev/./urandom", "app.jar"]
